### ISSUE TITLE
possible to choose colour and/or ... from group level

### ISSUE THREAD

**Issue by manco** [manco/three-sandbox#15]
8. Natomiast z pozycji wyżej będziemy wybierać kolor i uchwyty (tyko szafki).

**Comment by manco** [comment]
ok, wybieranie tekstury na poziomie grupy modulow gotowe. Sposób wyboru koloru (nowy dialog na warstwie) nie jest zbyt spójny z resztą interfejsu, ale póki co nie miałem lepszego pomysłu. Wrócimy do tego jak będzie więcej elementów.

**Comment by gtarchitekci** [comment]
Jest pięknie! Szczegóły graficzne dopracujemy na sam koniec.
