### ISSUE TITLE
kontrolki psuja sie po dluzszym uzywaniu

### ISSUE THREAD

**Issue by manco** [manco/three-sandbox#19]
Po dłuższym przebywaniu w planerze walą się funkcje. Naciskając przyciski przesuń model się obraca. Nie działa również centruj. Też tak masz?

_Originally posted by @gtarchitekci in https://github.com/manco/three-sandbox/issues/14#issuecomment-435710006_

**Comment by manco** [comment]
nie zauwazylem.

na telefonie czy komputerze?
ile to jest 'dluzej'?

**Comment by manco** [comment]
wydaje mi sie ze znalazlem (i rozwiazalem) problem: jesli kliknie sie w przestrzen zupelnie poza kuchnia (tzn. sprobuje zaznaczyc modul gdzies gdzie go nie ma) to w wyniku tego powstaja pozniej rozne bledy.

Poprawilem to zaznaczanie, powinno byc stabilnie

**Comment by gtarchitekci** [comment]
Jest stabilnie, można zamknąć wątek...
